<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ControlsanitarioPiscinas [
<!ELEMENT ControlsanitarioPiscinas (instalaciones)>
<!ELEMENT instalaciones (denominacion,titular,nif,domicilio,municipio,telefono,email,numPiscina,piscina,inspecciones)>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT titular (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT municipio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT numPiscina (temporada)>
<!ELEMENT piscina (idpiscina,denominacion,superficie,profundidad,cerramiento,tipopisci)>
<!ELEMENT inspecciones (inspeccion)>
<!ELEMENT temporada (apertura,cierre)>
<!ELEMENT idpiscina (#PCDATA)>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT idpiscina (#PCDATA)>
<!ELEMENT profundidad (#PCDATA)>
<!ELEMENT cerramiento (cubierta|descubierta|mixta|alterna)>
<!ELEMENT tipopisci (polivalente|enseñanza|chapoteo|recreo|natación|fososdesaltos|hidromasaje|terapéutico)>
<!ELEMENT inspeccion (fecha,deficiencias,calificacion,vaso)>
<!ELEMENT fecha (dia,mes,ano)>
<!ELEMENT deficiencias (sanitarias,higienicos,informacion,quimicos,personal)>
<!ELEMENT calificacion (Sindeficiencias|Deficienciasleve|Deficienciasgraves|Cierre|ProhibiciónTemporaldelbaño)>
<!ELEMENT vaso (deficiencias,resultado,cierre)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT sanitarias (#PCDATA)>
<!ELEMENT higienicos (#PCDATA)>
<!ELEMENT informacion (#PCDATA)>
<!ELEMENT quimicos (#PCDATA)>
<!ELEMENT personal (#PCDATA)>
<!ELEMENT deficiencias (controles,parametros,estructurales,depuracion)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT cierre (#PCDATA)>

<!ATTLIST numPiscina num CDATA #REQUIRED>
<!ATTLIST temporada tipo CDATA #REQUIRED>
<!ATTLIST inspeccion numero CDATA #REQUIRED>
<!ATTLIST temporada instalacion CDATA #REQUIRED>
<!ATTLIST vaso idpiscina CDATA #REQUIRED>
]>
<ControlsanitarioPiscinas>
	<instalaciones>
		<denominacion>baños paco</denominacion>
		<titular>Paco Gerte</titular>
		<nif>54023288B</nif>
		<domicilio>calle aladierna, 19</domicilio>
		<municipio>madrid</municipio>
		<telefono>696589555</telefono>
		<email>Pacobaños@gmail.com</email>
		<numPiscina num="2">
			<temporada tipo="anual"></temporada>
			<temporada tiipo="trimestral">
				<apertura>1 junio</apertura>
				<cierre>1 septiembre</cierre>
			</temporada>
		</numPiscina>
		<piscina>
			<idpiscina>1</idpiscina>
			<denominacion>piscinon</denominacion>
			<superficie>50m*25m</superficie>
			<profundidad>2,5m</profundidad>
			<cerramiento>cubierta</cerramiento>
			<tipopisci>polivalente</tipopisci>
		</piscina>
		<piscina>
			<idpiscina>2</idpiscina>
			<denominacion>comunidad</denominacion>
			<superficie>35m*30m</superficie>
			<profundidad>2,2m</profundidad>
			<cerramiento>exterior</cerramiento>
			<tipopisci>recrèo</tipopisci>
		</piscina>
		<inspecciones>
			<inspeccion numero="1" instalacion="baños paco">
				<fecha>
					<dia>3</dia>
					<mes>6</mes>
					<ano>2021</ano>
				</fecha>
				<deficiencias>
					<sanitarias>0</sanitarias>
					<higienicos>0</higienicos>
					<informacion>0</informacion>
					<quimicos>0</quimicos>
					<personal>0</personal>
				</deficiencias>
				<calificacion>Sin deficiencias</calificacion>
				<vaso idpiscina="1">
					<deficiencias>
						<controles>0</controles>
						<parametros>0</parametros>
						<estructurales>0</estructurales>
						<depuracion>0</depuracion>
					</deficiencias>
					<resultado>1</resultado>
					<cierre>0</cierre>
				</vaso>
				<vaso idpiscina="2">
					<deficiencias>
						<controles>0</controles>
						<parametros>0</parametros>
						<estructurales>0</estructurales>
						<depuracion>0</depuracion>
					</deficiencias>
					<resultado>1</resultado>
					<cierre>0</cierre>
				</vaso>
			</inspeccion>
		</inspecciones>
	</instalaciones>
</ControlsanitarioPiscinas>

