=== sergioromerohd/CPAD-1year-DAM-/1ºaño-1ºyear/Lenguaje de marcas- brand language/Ejercicios/Practicas/xml/practicaxmlxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ControlsanitarioPiscinas">
    <xs:complextype>
        <xs:sequence>
            <xs:element name="instalaciones">
                <xs:complextype>
                    <xs:sequence>
                        <xs:element name="denominacion" type="xs:string">
                        </xs:element>
                        <xs:element name="titular" type="xs:string">
                        </xs:element>
                        <xs:element name="nif" type="xs:string">
                        </xs:element>
                        <xs:element name="domicilio" type="xs:string">
                        </xs:element>
                        <xs:element name="municipio" type="xs:string">
                        </xs:element>
                        <xs:element name="telefono" type="xs:string">
                        </xs:element>
                        <xs:element name="email" type="xs:string">
                        </xs:element>
                        <xs:element name="numPiscina">
                            <xs:complextype>
                                <xs:sequence>
                                    <xs:element name="temporada">
                                        <xs:complextype>
                                            <xs:sequence>
                                                <xs:element name="apertura" type="xs:string"/>
                                                <xs:element name="cierre" type="xs:string"/>
                                            </xs:sequence>
                                        </xs:complextype>
                                        <xs:attribute name="tipo" type="xs:string"/>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complextype>
                            <xs:attribute name="num" type="xs:integer"/>
                        </xs:element>
                        <xs:element name="piscina">
                            <xs:complextype>
                                <xs:sequence>
                                    <xs:element name="idpiscina" type="xs:integer"/>
                                    <xs:element name="denominacion" type="xs:string"/>
                                    <xs:element name="superficie" type="xs:string"/>
                                    <xs:element name="profundidad" type="xs:string"/>
                                    <xs:element name="cerramiento" type="xs:string"/>
                                    <xs:element name="tipopisci" type="xs:string"/>
                                </xs:sequence>
                            </xs:complextype>
                        </xs:element>
                        <xs:element name="piscina">
                            <xs:complextype>
                                <xs:sequence>
                                    <xs:element name="idpiscina" type="xs:integer"/>
                                    <xs:element name="denominacion" type="xs:string"/>
                                    <xs:element name="superficie" type="xs:string"/>
                                    <xs:element name="profundidad" type="xs:string"/>
                                    <xs:element name="cerramiento" type="xs:string"/>
                                    <xs:element name="tipopisci" type="xs:string"/>
                                </xs:sequence>
                            </xs:complextype>
                        </xs:element>
                        <xs:element name="inspecciones">
                            <xs:complextype>
                                <xs:sequence>
                                    <xs:element name="inspeccion">
                                        <xs:complextype>
                                            <xs:sequence>
                                                <xs:element name="fecha">
                                                    <xs:complextype>
                                                        <xs:sequence>
                                                            <xs:element name="dia" type="xs:integer"/>
                                                            <xs:element name="mes" type="xs:integer"/>
                                                            <xs:element name="ano" type="xs:integer"/>
                                                        </xs:sequence>
                                                    </xs:complextype>
                                                </xs:element>
                                                <xs:element name="deficiencias">
                                                    <xs:complextype>
                                                        <xs:sequence>
                                                            <xs:element name="sanitarias" type="xs:boolean"/>
                                                            <xs:element name="higienicos" type="xs:boolean"/>
                                                            <xs:element name="informacion" type="xs:boolean"/>
                                                            <xs:element name="quimicos" type="xs:boolean"/>
                                                            <xs:element name="personal" type="xs:boolean"/>
                                                        </xs:sequence>
                                                    </xs:complextype>
                                                </xs:element>
                                                <xs:element name="calificacion" type="xs:string"/>
                                                <xs:element name="vaso">
                                                    <xs:complextype>
                                                        <xs:sequence>
                                                            <xs:element name="deficiencias">
                                                                <xs:complextype>
                                                                    <xs:sequence>
                                                                        <xs:element name="controles" type="xs:boolean"/>
                                                                        <xs:element name="parametros" type="xs:boolean"/>
                                                                        <xs:element name="estructurales" type="xs:boolean"/>
                                                                        <xs:element name="depuracion" type="xs:boolean"/>
                                                                    </xs:sequence>
                                                                </xs:complextype>
                                                            </xs:element>
                                                            <xs:element name="resultado" type="xs:integer"/>
                                                            <xs:element name="cierre" type="xs:boolean"/>
                                                        </xs:sequence>
                                                    </xs:complextype>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complextype>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complextype>
                            <xs:attribute name="numero" type="xs:integer"/>
                            <xs:attribute name="instalacion" type="xs:string"/>
                        </xs:element>
                    </xs:sequence>
                </xs:complextype>
            </xs:element>
        </xs:sequence>
    </xs:complextype>
   </xs:element>
</xs:schema>

=== sergioromerohd/CPAD-1year-DAM-/1ºaño-1ºyear/Lenguaje de marcas- brand language/Ejercicios/Practicas/xml/practica xml for xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
	<ControlsanitarioPiscinas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./practicaxmlxsd.xsd">
		<instalaciones>
			<denominacion>baños paco</denominacion>
			<titular>Paco Gerte</titular>
			<nif>54023288B</nif>
			<domicilio>calle aladierna, 19</domicilio>
			<municipio>madrid</municipio>
			<telefono>696589555</telefono>
			<email>Pacobaños@gmail.com</email>
			<numPiscina num="2">
				<temporada tipo="anual"></temporada>
				<temporada tipo="trimestral">
					<apertura>1 junio</apertura>
					<cierre>1 septiembre</cierre>
				</temporada>
			</numPiscina>
			<piscina>
				<idpiscina>1</idpiscina>
				<denominacion>piscinon</denominacion>
				<superficie>50m*25m</superficie>
				<profundidad>2,5m</profundidad>
				<cerramiento>cubierta</cerramiento>
				<tipopisci>polivalente</tipopisci>
			</piscina>
			<piscina>
				<idpiscina>2</idpiscina>
				<denominacion>comunidad</denominacion>
				<superficie>35m*30m</superficie>
				<profundidad>2,2m</profundidad>
				<cerramiento>exterior</cerramiento>
				<tipopisci>recrèo</tipopisci>
			</piscina>
			<inspecciones>
				<inspeccion numero="1" instalacion="baños paco">
					<fecha>
						<dia>3</dia>
						<mes>6</mes>
						<ano>2021</ano>
					</fecha>
					<deficiencias>
						<sanitarias>0</sanitarias>
						<higienicos>0</higienicos>
						<informacion>0</informacion>
						<quimicos>0</quimicos>
						<personal>0</personal>
					</deficiencias>
					<calificacion>Sin deficiencias</calificacion>
					<vaso idpiscina="1">
						<deficiencias>
							<controles>0</controles>
							<parametros>0</parametros>
							<estructurales>0</estructurales>
							<depuracion>0</depuracion>
						</deficiencias>
						<resultado>1</resultado>
						<cierre>0</cierre>
					</vaso>
					<vaso idpiscina="2">
						<deficiencias>
							<controles>0</controles>
							<parametros>0</parametros>
							<estructurales>0</estructurales>
							<depuracion>0</depuracion>
						</deficiencias>
						<resultado>1</resultado>
						<cierre>0</cierre>
					</vaso>
				</inspeccion>
			</inspecciones>
		</instalaciones>
	</ControlsanitarioPiscinas>
</xs:schema>
